---
- name: Скачиваем дистрибутив Lighthouse
  ansible.builtin.get_url:
    url: "https://github.com/VKCOM/lighthouse/archive/refs/heads/master.zip"
    dest: "./lighthouse.zip"

- name: Разархивируем дистрибутив Lighthouse в Nginx
  become: true
  ansible.builtin.unarchive:
    src: ./lighthouse.zip
    dest: /var/www/html/
    remote_src: true
  notify: Перезагрузка сервиса Nginx

- name: Make nginx config
  become: true
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Перезагрузка сервиса Nginx

- name: Удаление архива Lighthouse
  ansible.builtin.file:
    path: "./lighthouse.zip"
    state: absent